# Generated by Django 4.2.13 on 2024-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_validatorhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.IntegerField(default=-1)),
                ('validator_name', models.CharField(default='unknown', max_length=255)),
                ('node_address', models.CharField(max_length=255)),
                ('treasury', models.CharField(max_length=255)),
                ('commission_rate', models.CharField(max_length=255)),
                ('voting_power', models.CharField(default='0', max_length=255)),
                ('bonded_stake', models.CharField(max_length=255)),
                ('self_bonded_stake', models.CharField(max_length=255)),
                ('registration_block', models.CharField(max_length=255)),
                ('total_slashed', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oracle_address', models.CharField(max_length=255)),
                ('enode', models.CharField(max_length=255)),
                ('consensus_key', models.CharField(max_length=255)),
                ('provable_fault_count', models.CharField(max_length=255)),
                ('self_unbonding_stake', models.CharField(max_length=255)),
                ('self_unbonding_shares', models.CharField(max_length=255)),
                ('self_unbonding_stake_locked', models.CharField(max_length=255)),
                ('unbonding_stake', models.CharField(max_length=255)),
                ('unbonding_shares', models.CharField(max_length=255)),
                ('liquid_contract', models.CharField(max_length=255)),
                ('liquid_supply', models.CharField(max_length=255)),
                ('jail_release_block', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('discord', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('covered', models.BooleanField(default=False)),
            ],
        ),
    ]
