# Generated by Django 4.2.13 on 2024-07-11 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0003_validatorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='delegated_stake_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=list), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='validator',
            name='self_bonded_stake_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=list), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='validator',
            name='total_slashed_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=list), blank=True, default=list, size=None),
        ),
    ]
