# Generated by Django 4.2.13 on 2024-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0004_validator_delegated_stake_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='covered',
            field=models.BooleanField(default=False),
        ),
    ]
