# Generated by Django 4.2.13 on 2024-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutonityNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=255, unique=True)),
                ('network_name', models.CharField(max_length=255)),
                ('rpc_url', models.URLField()),
                ('symbol', models.CharField(max_length=10)),
                ('isHistoricActive', models.BooleanField(default=False)),
            ],
        ),
    ]
