from django.db import models
from django.contrib.postgres.fields import ArrayField

class Validator(models.Model):
    chain_id = models.IntegerField(default=-1)
    validator_name = models.CharField(max_length=255, default='unknown')
    node_address = models.CharField(max_length=255)
    treasury = models.CharField(max_length=255)
    commission_rate = models.CharField(max_length=255)
    commission_rate_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    voting_power = models.CharField(max_length=255, default='0')
    voting_power_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    bonded_stake = models.CharField(max_length=255)
    bonded_stake_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    self_bonded_stake = models.CharField(max_length=255)
    self_bonded_stake_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    delegated_stake_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    registration_block = models.CharField(max_length=255)
    total_slashed = models.CharField(max_length=255)
    total_slashed_history = ArrayField(models.JSONField(blank=True, default=list), blank=True, default=list)
    state = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    oracle_address = models.CharField(max_length=255)
    enode = models.CharField(max_length=255)
    consensus_key = models.CharField(max_length=255)
    provable_fault_count = models.CharField(max_length=255)
    self_unbonding_stake = models.CharField(max_length=255)
    self_unbonding_shares = models.CharField(max_length=255)
    self_unbonding_stake_locked = models.CharField(max_length=255)
    unbonding_stake = models.CharField(max_length=255)
    unbonding_shares = models.CharField(max_length=255)
    liquid_contract = models.CharField(max_length=255)
    liquid_supply = models.CharField(max_length=255)
    jail_release_block = models.CharField(max_length=255)
    covered = models.BooleanField(default=False)

class ValidatorInfo(models.Model):
    chain_id = models.IntegerField(default=-1)
    validator_name = models.CharField(max_length=255, default='unknown')
    node_address = models.CharField(max_length=255)
    treasury = models.CharField(max_length=255)
    commission_rate = models.CharField(max_length=255)
    voting_power = models.CharField(max_length=255, default='0')
    bonded_stake = models.CharField(max_length=255)
    self_bonded_stake = models.CharField(max_length=255)
    registration_block = models.CharField(max_length=255)
    total_slashed = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    oracle_address = models.CharField(max_length=255)
    enode = models.CharField(max_length=255)
    consensus_key = models.CharField(max_length=255)
    provable_fault_count = models.CharField(max_length=255)
    self_unbonding_stake = models.CharField(max_length=255)
    self_unbonding_shares = models.CharField(max_length=255)
    self_unbonding_stake_locked = models.CharField(max_length=255)
    unbonding_stake = models.CharField(max_length=255)
    unbonding_shares = models.CharField(max_length=255)
    liquid_contract = models.CharField(max_length=255)
    liquid_supply = models.CharField(max_length=255)
    jail_release_block = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    website = models.CharField(max_length=255)
    telegram = models.CharField(max_length=255)
    x = models.CharField(max_length=255)
    discord = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    covered = models.BooleanField(default=False)


class ValidatorHistory(models.Model):
    validator_id = models.ForeignKey(Validator, on_delete=models.CASCADE)
    chain_id = models.IntegerField()
    validator_name = models.CharField(max_length=255)
    node_address = models.CharField(max_length=255)
    treasury = models.CharField(max_length=255)
    commission_rate = models.CharField(max_length=255)
    voting_power = models.CharField(max_length=255, default='0')
    bonded_stake = models.CharField(max_length=255)
    total_slashed = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    history_created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    oracle_address = models.CharField(max_length=255)
    enode = models.CharField(max_length=255)
    consensus_key = models.CharField(max_length=255)
    provable_fault_count = models.CharField(max_length=255)
    self_unbonding_stake = models.CharField(max_length=255)
    self_unbonding_shares = models.CharField(max_length=255)
    self_unbonding_stake_locked = models.CharField(max_length=255)
    unbonding_stake = models.CharField(max_length=255)
    unbonding_shares = models.CharField(max_length=255)
    liquid_contract = models.CharField(max_length=255)
    liquid_supply = models.CharField(max_length=255)
    jail_release_block = models.CharField(max_length=255)
